apiVersion: v1
kind: Service
metadata:
  name: {{ template "test-apache.fullname" . }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ .Values.global.service.port }}
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/name: {{ template "test-apache.fullname" . }}
