apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.global.env }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: test-apache.{{ .Values.global.env }}.{{ .Values.global.domain }}
    http:
      paths:
      - path: /?(index.html)
        backend:
          serviceName: {{ template "test-apache.fullname" . }}
          servicePort: {{ .Values.global.service.port }}
  tls:
  - hosts:
    - test-apache.{{ .Values.global.env }}.{{ .Values.global.domain }}
    secretName: tls-test-secret
    #secretName: tls-{{ .Values.global.env }}-secret
