apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.global.env }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
  - http:
      paths:
      - path: /?(index.html)
        backend:
          serviceName: {{ template "test-apach.fullname" . }}
          servicePort: {{ .Values.global.service.port }}
